id: A3FD6D39A
title: Prayer for the Swift Rebirth of Khandro Tsering Chödrön
type: translation
pechas:
- I352DB422
- IF886F88D
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:48:57.528140
  last_modified_at: 2023-01-04 12:48:57.528163
  collections:
  - Khandro Tsering Chödrön Series
  - Works of Tibetan Masters
alignment_to_base:
  I352DB422/F8FF: 0E74
  IF886F88D/4459: 0E74
